"use strict";
const {test} = require("node:test");
const assert = require("node:assert/strict");
const {createApp} = require("../server");
const {createServer} = require("node:http");
const {randomBytes, createHash} = require("node:crypto");
const fs = require("node:fs"), os = require("node:os"), path = require("node:path");
const {spawn} = require("node:child_process");
const token = "guest-test-admin-".repeat(4);
const key = () => randomBytes(32).toString("hex");
const hash = value => createHash("sha256").update(value).digest("hex");
async function fixture(t) {
  const server = createServer();
  await new Promise(resolve => server.listen(0,"127.0.0.1",resolve));
  const url = "http://127.0.0.1:" + server.address().port;
  const runtime = await createApp({token, dbPath: ":memory:", baseUrl: url});
  server.on("request", runtime.app);
  t.after(() => new Promise(resolve => { server.close(() => {runtime.db.close();resolve();}); server.closeIdleConnections(); }));
  async function call(endpoint, body, auth = token, origin = url) {
    return fetch(url + endpoint, {method: body === undefined ? "GET" : "POST", headers: {Origin: origin, "Content-Type": "application/json", ...(auth ? {Authorization: "Bearer " + auth} : {})}, body: body === undefined ? undefined : JSON.stringify(body)});
  }
  async function invite() {const r = await call("/api/v1/invites", {label:"Guest QA"});assert.equal(r.status,201);return r.json();}
  async function accept() {const invitation=await invite(), apiToken=key();const r=await call("/auth/accept", {invite:invitation.code, apiToken}, apiToken);assert.equal(r.status,201,await r.clone().text());return {apiToken, invitation, member:(await (await call("/api/v1/me",undefined,apiToken)).json()).member};}
  return {...runtime,url,call,invite,accept};
}
test("guest invitations require permission, are single-use, and later registration preserves ownership",async t => {
  const {call,invite,accept,db,url} = await fixture(t);
  assert.equal((await call("/auth/accept",{invite:"missing"},null)).status,410);
  const invitation=await invite();
  assert.equal((await call("/auth/accept",{invite:invitation.code},null,"https://other.example")).status,403);
  const r=await call("/auth/accept",{invite:invitation.code},null);
  assert.equal(r.status,201);
  const cookie=r.headers.get("set-cookie").split(";")[0];
  const guest=await (await fetch(url+"/api/v1/me",{headers:{Cookie:cookie}})).json();
  assert.equal(guest.member.registered,false);
  assert.equal(guest.member.admin,false);
  assert.equal(db.prepare("SELECT password FROM members WHERE id=?").get(guest.member.id).password,null);
  assert.equal((await call("/auth/accept",{invite:invitation.code,apiToken:key()},null)).status,410);
  const a=await accept(), b=await accept();
  assert.equal((await call("/api/v1/invites",{label:"forbidden"},a.apiToken)).status,403);
  const write=await fetch(url+"/api/v1/works/guest-page",{method:"PUT",headers:{Authorization:"Bearer "+a.apiToken,"Content-Type":"application/json"},body:JSON.stringify({title:"Guest work",html:"<h1>Guest</h1>"})});
  assert.equal(write.status,201,await write.clone().text());
  assert.equal((await call("/api/v1/works/guest-page",undefined,b.apiToken)).status,404);
  assert.equal((await call("/api/v1/password",{username:"guestqa",password:"guest-password-12345"},a.apiToken)).status,200);
  const now=(await (await call("/api/v1/me",undefined,a.apiToken)).json()).member;
  assert.equal(now.id,a.member.id);assert.equal(now.registered,true);assert.equal(now.username,"guestqa");
  assert.equal((await call("/api/v1/works/guest-page",undefined,a.apiToken)).status,200);
  assert.equal((await call("/auth/login",{username:"guestqa",password:"guest-password-12345"},null)).status,200);
  assert.equal((await call("/api/v1/password",{username:"changedname",password:"guest-password-12345"},a.apiToken)).status,200);
});
test("Agent pairing preserves space, retries safely, hashes secrets and revokes old connections",async t => {
  const {call,accept,db,url}=await fixture(t);
  const a=await accept();
  const count=db.prepare("SELECT count(*) n FROM members").get().n;
  assert.equal((await call("/auth/accept",{invite:a.invitation.code,apiToken:a.apiToken},a.apiToken)).status,200);
  assert.equal(db.prepare("SELECT count(*) n FROM members").get().n,count);
  const pair=async () => {const r=await call("/api/v1/agent-grant",{},a.apiToken);assert.equal(r.status,200);assert.equal(r.headers.get("cache-control"),"no-store");return (await r.json()).prompt.match(/本次连接码：([a-f0-9]{64})/)[1];};
  const code=await pair(), second=key();
  assert.equal((await call("/auth/connect",{code,apiToken:second},second,"https://other.example")).status,403);
  assert.equal((await call("/auth/connect",{code,apiToken:second},second)).status,200);
  assert.equal((await call("/auth/connect",{code,apiToken:second},second)).status,200);
  assert.equal((await call("/auth/connect",{code,apiToken:key()},null)).status,410);
  assert.equal((await (await call("/api/v1/me",undefined,second)).json()).member.id,a.member.id);
  assert.equal((await call("/api/v1/me",undefined,a.apiToken)).status,200);
  const stored=JSON.stringify(db.prepare("SELECT * FROM api_keys").all());
  assert.ok(!stored.includes(a.apiToken)&&!stored.includes(second));assert.ok(stored.includes(hash(second)));
  const expired=await pair();db.prepare("UPDATE agent_grants SET expires=0").run();
  assert.equal((await call("/auth/connect",{code:expired,apiToken:key()},null)).status,410);
  const pending=await pair();
  const rotated=await (await call("/api/v1/key",{},a.apiToken)).json();
  assert.equal((await call("/api/v1/me",undefined,a.apiToken)).status,401);
  assert.equal((await call("/api/v1/me",undefined,second)).status,401);
  assert.equal((await call("/auth/connect",{code:pending,apiToken:key()},null)).status,410);
  assert.equal((await call("/api/v1/me",undefined,rotated.token)).status,200);
  const response=await fetch(url+"/api/v1/members/"+a.member.id,{method:"PATCH",headers:{Authorization:"Bearer "+token,"Content-Type":"application/json"},body:'{"disabled":true}'});
  assert.equal(response.status,200);assert.equal((await call("/api/v1/me",undefined,rotated.token)).status,401);
});
test("downloaded CLI redeems invitation through stdin, retains private config and resumes a lost response",async t => {
  const {call,invite,db,url}=await fixture(t);
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),"qs-guest-cli-"));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
  const cli=path.join(dir,"quickshare.js"), config=path.join(dir,"private/config.json");
  fs.writeFileSync(cli,await (await call("/client/quickshare.js")).text());
  const run=(args,input="",configPath=config)=>new Promise(resolve=>{
    const child=spawn(process.execPath,[cli,...args],{cwd:dir,env:{...process.env,QUICKSHARE_CONFIG:configPath,QUICKSHARE_URL:"",QUICKSHARE_TOKEN:""}});let stdout="",stderr="";
    child.stdout.on("data",x=>stdout+=x);child.stderr.on("data",x=>stderr+=x);child.stdin.on("error",()=>{});child.stdin.end(input);child.on("close",code=>resolve({code,stdout,stderr}));
  });
  const invitation=await invite();
  const joined=await run(["join","--url",url,"--invite-stdin"],invitation.url);
  assert.equal(joined.code,0,joined.stderr);
  const saved=JSON.parse(fs.readFileSync(config));assert.equal(saved.pending,undefined);assert.equal(fs.statSync(config).mode&0o777,0o600);
  assert.ok(!joined.stdout.includes(saved.token)&&!joined.stderr.includes(saved.token)&&!joined.stdout.includes(invitation.code));
  const me=await run(["doctor","--json"]);assert.equal(me.code,0,me.stderr);assert.equal(JSON.parse(me.stdout).member.registered,false);
  const unused=await invite();assert.equal((await run(["join","--url",url,"--invite-stdin"],unused.code)).code,0);
  assert.equal(db.prepare("SELECT used FROM invites WHERE hash=?").get(hash(unused.code.replaceAll("-",""))).used,0);
  const original=fs.readFileSync(config,"utf8");assert.notEqual((await run(["join","--url","https://other.example","--invite-stdin"],unused.code)).code,0);assert.equal(fs.readFileSync(config,"utf8"),original);
  const pendingKey=key(), pendingPath=path.join(dir,"pending.json");
  assert.equal((await call("/auth/accept",{invite:unused.code,apiToken:pendingKey},pendingKey)).status,201);
  fs.writeFileSync(pendingPath,JSON.stringify({url,token:pendingKey,pending:true}),{mode:0o600});
  const retry=await run(["join","--url",url,"--invite-stdin"],unused.code,pendingPath);assert.equal(retry.code,0,retry.stderr);assert.equal(JSON.parse(fs.readFileSync(pendingPath)).token,pendingKey);assert.equal(JSON.parse(fs.readFileSync(pendingPath)).pending,undefined);
  const grant=await (await call("/api/v1/agent-grant",{},saved.token)).json();
  const connect=await run(["connect","--url",url,"--code-stdin"],grant.prompt.match(/本次连接码：([a-f0-9]{64})/)[1],path.join(dir,"second.json"));assert.equal(connect.code,0,connect.stderr);
  const rotated=(await (await call("/api/v1/key",{},saved.token)).json()).token;
  const fresh=(await (await call("/api/v1/agent-grant",{},rotated)).json()).prompt.match(/本次连接码：([a-f0-9]{64})/)[1];
  const reconnected=await run(["connect","--url",url,"--code-stdin"],fresh);
  assert.equal(reconnected.code,0,reconnected.stderr);
  assert.notEqual(JSON.parse(fs.readFileSync(config)).token,saved.token);
  const backup=fs.readdirSync(path.dirname(config)).find(name=>name.startsWith("config.json.revoked-"));
  assert.ok(backup);assert.equal(fs.statSync(path.join(path.dirname(config),backup)).mode&0o777,0o600);
  assert.equal(JSON.parse(fs.readFileSync(path.join(path.dirname(config),backup))).token,saved.token);
});
test("expired, revoked and legacy invitations and connection limits retain their boundaries",async t=>{
  const {call,db,invite,accept}=await fixture(t);
  const expired=await invite();db.prepare("UPDATE invites SET expires=0 WHERE hash=?").run(hash(expired.code.replaceAll("-","")));
  assert.equal((await call("/auth/accept",{invite:expired.code},null)).status,410);
  const revoked=await invite();db.prepare("DELETE FROM invites WHERE hash=?").run(hash(revoked.code.replaceAll("-","")));
  assert.equal((await call("/auth/accept",{invite:revoked.code},null)).status,410);
  const legacy=key();db.prepare("INSERT INTO invites(hash,label,expires) VALUES(?,?,?)").run(hash(legacy),"legacy fixture",Date.now()+60000);
  assert.equal((await call("/auth/accept",{invite:legacy,apiToken:key()},null)).status,201);
  const a=await accept();
  for(let i=0;i<9;i++) db.prepare("INSERT INTO api_keys VALUES(?,?,?)").run(hash(key()),a.member.id,Date.now());
  const prompt=(await (await call("/api/v1/agent-grant",{},a.apiToken)).json()).prompt;
  const code=prompt.match(/本次连接码：([a-f0-9]{64})/)[1];
  assert.equal((await call("/auth/connect",{code,apiToken:key()},null)).status,409);
  assert.ok(db.prepare("SELECT hash FROM agent_grants WHERE hash=?").get(hash(code)));
  assert.equal(db.prepare("SELECT count(*) n FROM api_keys WHERE member_id=?").get(a.member.id).n,10);
});
test("friends list keeps the invitation identity, private note and work count after optional registration", async t => {
  const {call,invite,db,url} = await fixture(t);
  const invitation = await invite();
  const rows = async () => (await (await call("/api/v1/friends")).json()).friends;
  const pending = (await rows())[0];
  assert.equal(pending.id, invitation.id);assert.equal(pending.state,"pending");
  assert.equal((await call("/api/v1/friends",undefined,null)).status,401);
  const apiToken=key();
  assert.equal((await call("/auth/accept",{invite:invitation.code,apiToken},apiToken)).status,201);
  const joined=(await rows())[0];
  assert.equal(joined.id,pending.id);assert.equal(joined.note,"Guest QA");assert.equal(joined.state,"joined");
  assert.equal((await call("/api/v1/friends",undefined,apiToken)).status,403);
  assert.equal((await call("/api/v1/members/"+joined.member_id+"/recovery",{},apiToken)).status,403);
  const patch=async (body,auth=token)=>fetch(url+"/api/v1/members/"+joined.member_id,{method:"PATCH",headers:{Authorization:"Bearer "+auth,"Content-Type":"application/json"},body:JSON.stringify(body)});
  assert.equal((await patch({note:"private-design-friend"},apiToken)).status,403);
  assert.equal((await patch({note:"private-design-friend"})).status,200);
  assert.equal((await call("/api/v1/me",undefined,apiToken)).status,200);
  assert.equal((await rows())[0].note,"private-design-friend");
  assert.equal((await call("/api/v1/password",{username:"friendly",password:"strong-password-123"},apiToken)).status,200);
  assert.equal((await rows())[0].id,pending.id);assert.equal((await rows())[0].note,"private-design-friend");
  const work=await fetch(url+"/api/v1/works/friend-identity",{method:"PUT",headers:{Authorization:"Bearer "+apiToken,"Content-Type":"application/json"},body:JSON.stringify({title:"My page",html:"<h1>hello</h1>"})});assert.equal(work.status,201);
  assert.equal((await rows())[0].works_count,1);
  assert.ok((await (await call("/api/v1/works?all=true")).text()).includes("private-design-friend"));
  for (const endpoint of ["/api/v1/me","/api/v1/works?all=true","/api/v1/works"]) assert.ok(!(await (await call(endpoint,undefined,apiToken)).text()).includes("private-design-friend"));
  assert.equal(db.prepare("SELECT member_id FROM invites WHERE invite_id=?").get(invitation.id).member_id,joined.member_id);
});
test("reissuing and revoking preserve one friend row and invalidate every old invitation copy",async t=>{
  const {call,invite,db,url}=await fixture(t);
  const invitation=await invite();
  db.prepare("UPDATE invites SET expires=0 WHERE invite_id=?").run(invitation.id);
  assert.equal((await (await call("/api/v1/friends")).json()).friends[0].state,"expired");
  const fresh=await (await call("/api/v1/invites/"+invitation.id+"/reissue",{})).json();
  assert.equal(fresh.id,invitation.id);assert.notEqual(fresh.code,invitation.code);
  assert.equal((await call("/auth/accept",{invite:invitation.code},null)).status,410);
  assert.equal((await fetch(url+"/api/v1/invites/"+invitation.id,{method:"DELETE",headers:{Authorization:"Bearer "+token}})).status,200);
  assert.equal((await (await call("/api/v1/friends")).json()).friends[0].state,"revoked");
  assert.equal((await call("/auth/accept",{invite:fresh.code},null)).status,410);
  const restored=await (await call("/api/v1/invites/"+invitation.id+"/reissue",{})).json();
  const accepted=await call("/auth/join",{invite:restored.code,username:"legacyfriend",password:"strong-password-123"},null);assert.equal(accepted.status,201);
  const rows=(await (await call("/api/v1/friends")).json()).friends;
  assert.equal(rows.length,1);assert.equal(rows[0].id,invitation.id);assert.equal(rows[0].state,"joined");
  assert.equal((await call("/api/v1/invites/"+invitation.id+"/reissue",{})).status,409);
});
test("recovery reconnects the original member, revokes only on redemption and is one-use and retry-safe",async t=>{
  const {call,accept,db,url}=await fixture(t);
  const a=await accept();
  const savedWork=await fetch(url+"/api/v1/works/keep-on-recovery",{method:"PUT",headers:{Authorization:"Bearer "+a.apiToken,"Content-Type":"application/json"},body:JSON.stringify({title:"Keep my work",html:"<h1>Preserved</h1>"})});
  assert.equal(savedWork.status,201);
  const recoveryPath="/api/v1/members/"+a.member.id+"/recovery";
  assert.equal((await call("/api/v1/members/1/recovery",{})).status,400);
  const grant=await (await call(recoveryPath,{})).json();
  assert.ok(grant.prompt.includes("24 小时"));assert.ok(!grant.prompt.includes("Guest QA"));
  assert.equal((await call("/api/v1/me",undefined,a.apiToken)).status,200);
  const obsolete=grant.prompt.match(/本次连接码：([a-f0-9]{64})/)[1];
  const current=await (await call(recoveryPath,{})).json();
  assert.equal((await call("/auth/connect",{code:obsolete,apiToken:key()},null)).status,410);
  const code=current.prompt.match(/本次连接码：([a-f0-9]{64})/)[1],newKey=key();
  assert.equal((await call("/auth/connect",{code,apiToken:newKey},newKey,"https://other.example")).status,403);
  assert.equal((await call("/api/v1/me",undefined,a.apiToken)).status,200);
  const linked=await (await call("/api/v1/dashboard-link",{},a.apiToken)).json();
  const login=await call("/auth/grant",{code:new URL(linked.url).hash.slice(6)},null);
  const cookie=login.headers.get("set-cookie").split(";")[0];
  const count=db.prepare("SELECT count(*) n FROM members").get().n;
  assert.equal((await call("/auth/connect",{code,apiToken:newKey},newKey)).status,200);
  assert.equal((await call("/api/v1/me",undefined,a.apiToken)).status,401);
  assert.equal((await fetch(url+"/api/v1/me",{headers:{Cookie:cookie}})).status,401);
  assert.equal((await (await call("/api/v1/me",undefined,newKey)).json()).member.id,a.member.id);
  assert.equal(db.prepare("SELECT count(*) n FROM members").get().n,count);
  const preserved=(await (await call("/api/v1/works/keep-on-recovery",undefined,newKey)).json()).work;
  assert.equal(preserved.owner_id,a.member.id);assert.equal(preserved.title,"Keep my work");
  assert.equal((await call("/auth/connect",{code,apiToken:newKey},newKey)).status,200);
  assert.equal((await call("/auth/connect",{code,apiToken:key()},null)).status,410);
  await fetch(url+"/api/v1/members/"+a.member.id,{method:"PATCH",headers:{Authorization:"Bearer "+token,"Content-Type":"application/json"},body:'{"disabled":true}'});
  assert.equal((await call(recoveryPath,{})).status,409);
});
